/*L
   Copyright Washington University in St. Louis
   Copyright SemanticBits
   Copyright Persistent Systems
   Copyright Krishagni

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/catissue_migration_tool/LICENSE.txt for details.
L*/

CREATE SEQUENCE MIGRATION_MAPPING_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE MIGRATION_EX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE MIGRATION_MAPPING 
(
	IDENTIFIER NUMBER(30,0) NOT NULL ENABLE, 
	OBJECT_CLASSNAME VARCHAR2(4000 BYTE), 
	OLD_ID NUMBER(30,0), 
	NEW_ID NUMBER(30,0), 
	CONSTRAINT MIGRATION_MAPPING_PK PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE MIGRATION_EXCEPTION
(
	IDENTIFIER NUMBER(30,0) NOT NULL ENABLE, 
	CLASSNAME VARCHAR2(4000 BYTE), 
	SANDBOXID NUMBER(30,0), 
	MESSAGE VARCHAR2(4000 BYTE), 
	STACKTRACE VARCHAR2(4000 BYTE), 
	CONSTRAINT MIGRATION_EXCEPTION_PK PRIMARY KEY (IDENTIFIER)
);