CREATE SEQUENCE CATISSUE_BULK_OPERATION_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE JOB_DETAILS_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

create table catissue_bulk_operation 
(
	IDENTIFIER number(19,0) not null,
	OPERATION VARCHAR(255) not null unique,
	CSV_TEMPLATE VARCHAR(2000) not null,
	XML_TEMPALTE CLOB not null,
	DROPDOWN_NAME VARCHAR(100) not null unique,
	CONSTRAINT CATISSUE_BULK_OPERATION_SEQ PRIMARY KEY (IDENTIFIER)
);
CREATE TABLE JOB_DETAILS (
  IDENTIFIER NUMBER(38) NOT NULL,
  JOB_NAME varchar(255) NOT NULL,
  JOB_STATUS varchar(50) default NULL,
  TOTAL_RECORDS_COUNT NUMBER(20) default NULL,
  FAILED_RECORDS_COUNT NUMBER(20) default NULL,
  TIME_TAKEN NUMBER(20) default NULL,
  LOG_FILE blob,
  JOB_STARTED_BY NUMBER(20) default NULL,
  START_TIME date default NULL,
  CURRENT_RECORDS_PROCESSED NUMBER(20) default NULL,
  LOG_FILE_NAME varchar(50) default NULL,
  PRIMARY KEY  (IDENTIFIER) 
);